ItemEvents.tooltip(event =>{
    event.add("cataclysm:mechanical_fusion_anvil","可以在精灵界亚尔夫海姆的腐化圣泉结构中找到，用于合成高阶武器和增强饰品")
    event.add("kubejs:random_pet_bag","§d在玩家位置生成一只随机的魔宠，使用奥术源质来驯服!")
    event.add("kubejs:dungeons_hearthstone","使用秘境炉石来返回试炼秘境维度")
    event.add("kubejs:dungeons_hearthstone_water","使用秘境炉石来返回试炼秘境维度,再灌点水...?")
    event.add("kubejs:dungeons_reward_bag_mine","打开奖励袋获取一些矿石或其他石材，有概率开出钻石和下界合金等稀有矿物！")
    event.add("kubejs:dungeons_reward_bag_upgrade_materail","打开奖励袋获取一些神化强化素材，有概率获得符石和高级素材!")
    event.add("kubejs:dungeons_reward_bag_tech","打开奖励袋获取一些植物魔法/机械动力实用道具!")
    event.add("#kubejs:epic_weapon_bag","打开包裹领取史诗武器！")
    event.add("kubejs:dungeons_reward_coin","在秘境商人处兑换各种物资")
    event.add("kubejs:dungeons_reward_coin_stack","在秘境商人处兑换各种物资")
    event.add("kubejs:zombie_summoner","生成一只测试监守者，用于测试DPS")
    event.add("kubejs:mana_diamond_sheet","灌注了魔力的钻石拥有耐压的特性，可被压成片板")
    event.add("kubejs:custom_dungeons_ring","秘境挑战者的专属奖赏戒指")
    event.add("kubejs:botanicreator_ring","一位优秀的植物魔法机械师的认证")
    event.add("item.kubejs.final_key.desc","§6使用终焉之钥移除出生点传送阵的屏障封印")
})